# Generated by Django 5.1.2 on 2024-10-29 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_consulta', models.DateField()),
                ('horario_consulta', models.TimeField()),
                ('status', models.CharField(choices=[('marcada', 'Marcada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_de_nascimento', models.DateField()),
                ('senha', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('gestao', 'Gestão')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_envio', models.DateTimeField()),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('pendente', 'Pendente')], max_length=10)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='agendamento.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_cliente', to='agendamento.usuario'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_profissional', to='agendamento.usuario'),
        ),
    ]
